version: "3.9"

services:
  app:
    image: ghcr.io/people-11/stickerdownloader:latest
    container_name: sticker_app
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./.env:/app/.env:ro
      - ./log:/app/log
      - ./storage:/app/storage
      - redis_data:/app/redis_data

volumes:
  redis_data:
